services:
  backend:
    build: ./qy_backend
    image: backend:latest
    container_name: backend
    restart: always
    volumes:
      # 数据持久化挂载
      - screenshots_volume:/app/qy_backend/media/screenshots
    env_file:
      - ./qy_backend/.env
    ports:
      - "8000:8000"   # 后端暴露接口
    networks:
      - appnet

  celery:
    #build: ./qy_backend
    image: backend:latest
    container_name: celery
    restart: always
    # 解决webkit 2 png截图报错问题
    shm_size: '1gb'
    working_dir: /app/qy_backend
    env_file:
      - ./qy_backend/.env
    entrypoint: []
    command: ["celery","-A","qy_backend.celery:app","worker","--loglevel=info"]
    volumes:
      - .:/app
      - ./logs/celery:/app/logs/celery
      # 数据持久化挂载
      - screenshots_volume:/app/qy_backend/media/screenshots
    depends_on:
      - backend
    networks:
      - appnet

  celery_beat:
    #build: ./qy_backend
    image: backend:latest
    container_name: celery-beat
    restart: always
    working_dir: /app/qy_backend
    env_file:
      - ./qy_backend/.env
    entrypoint: []
    command: ["celery","-A","qy_backend.celery:app","beat","--loglevel=info","--logfile=/app/logs/celery/celery-beat.log"]
    volumes:
      - .:/app
      - ./logs/celery:/app/logs/celery
      # 数据持久化挂载
      - screenshots_volume:/app/qy_backend/media/screenshots
    depends_on:
      - celery
    networks:
      - appnet

volumes:
  screenshots_volume:
    driver: local

# 网络配置
networks:
  appnet:
#    driver: bridge
    external: true
