services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    # 针对Mac M1/M2芯片的兼容性设置
    platform: linux/amd64
    restart: always
    environment:
      # MySQL 8默认使用caching_sha2_password认证插件
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: easy_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      # 字符集设置
      MYSQL_INITDB_ARGS: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      # 端口映射，允许宿主机访问
      - "33061:3306"
      - "33060:33060"  # MySQL 8的X协议端口
    volumes:
      # 数据持久化挂载
      - ./docker-data/mysql-data:/var/lib/mysql
      # 配置文件挂载
      - ./docker-data/mysql-conf:/etc/mysql/conf.d
      # 初始化脚本目录
      - ./docker-data/mysql-init:/docker-entrypoint-initdb.d
    # 资源限制，防止过度占用Mac资源
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    # Mac上的性能优化
    command: --default-authentication-plugin=caching_sha2_password
             --max_allowed_packet=64M
             --innodb_buffer_pool_size=256M
    networks:
      - appnet

# 网络配置
networks:
  appnet:
#    driver: bridge
    external: true
