services:

# API测试前端服务
  api-test:
    build: .
    container_name: api-test-container
    restart: always
    ports:
      - "80:80"
    networks:
      - appnet
    # 加载环境变量文件
    env_file:
      - .env

    # 显式传递环境变量到容器
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_LOGO_URL=${VITE_LOGO_URL}
      - VITE_FILE_BASE_URL=${VITE_FILE_BASE_URL}
